"""Answer composition service using LangChain + OpenAI.

Loads prompt templates, assembles context from ranked chunks,
calls the LLM, and returns a complete ChatResponse.

TODO: Implement streaming support for long responses.
TODO: Add response caching for identical query+context hashes.
"""

from __future__ import annotations

import logging
import time
import uuid
from pathlib import Path
from typing import Optional

from apps.api.schemas.chat import ChatResponse, Citation, SafetyFlag
from apps.api.schemas.patient_case import PatientCase
from apps.api.schemas.source import NormalizedChunk

logger = logging.getLogger(__name__)

# Prompt template paths
_PROMPTS_DIR = Path(__file__).parents[4] / "prompts"
_CLINICIAN_ANSWER_PROMPT = _PROMPTS_DIR / "generation" / "clinician_answer.txt"
_SAFETY_GUARDRAILS_PROMPT = _PROMPTS_DIR / "generation" / "safety_guardrails.txt"

_STANDARD_DISCLAIMER = (
    "This response is generated by REGENOVA-Intel, a clinical decision support tool. "
    "It does not constitute medical advice, diagnosis, or treatment. "
    "All information must be reviewed and validated by a qualified healthcare professional "
    "before clinical application."
)

_ESCALATED_DISCLAIMER = (
    "⚠️ IMPORTANT SAFETY NOTICE: This query has triggered one or more critical safety flags. "
    "The information below must NOT be used to guide clinical decisions without specialist consultation. "
    + _STANDARD_DISCLAIMER
)


def _load_prompt(path: Path) -> str:
    """Load a prompt template from disk, returning empty string if not found."""
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        logger.warning("Prompt template not found: %s", path)
        return ""


def _build_context_block(chunks: list[NormalizedChunk]) -> str:
    """Format retrieved chunks into a numbered context block for the LLM."""
    if not chunks:
        return "No relevant sources retrieved."

    lines: list[str] = []
    for i, chunk in enumerate(chunks, start=1):
        tier = chunk.metadata.evidence_tier_default
        source = chunk.metadata.source_name
        lines.append(f"[Source {i}] (Tier {tier}, {source})")
        lines.append(chunk.content.strip())
        lines.append("")

    return "\n".join(lines)


class AnswerComposer:
    """Composes the final ChatResponse by calling the LLM with assembled context.

    Uses LangChain's ChatOpenAI for LLM calls with the clinician answer prompt
    template. If critical safety flags are present, the safety guardrails
    prompt is injected as an additional system message.
    """

    def __init__(
        self,
        model: str = "gpt-4o",
        temperature: float = 0.1,
        openai_api_key: str = "",
    ) -> None:
        """Initialise AnswerComposer with LLM configuration.

        Args:
            model: OpenAI model name.
            temperature: Sampling temperature (low = more deterministic).
            openai_api_key: OpenAI API key.
        """
        self.model = model
        self.temperature = temperature
        self.openai_api_key = openai_api_key
        self._system_prompt = _load_prompt(_CLINICIAN_ANSWER_PROMPT)
        self._safety_guardrails = _load_prompt(_SAFETY_GUARDRAILS_PROMPT)

    def compose(
        self,
        query: str,
        ranked_chunks: list[tuple[NormalizedChunk, float]],
        citations: list[Citation],
        safety_flags: list[SafetyFlag],
        patient_case: Optional[PatientCase] = None,
        request_id: Optional[str] = None,
    ) -> ChatResponse:
        """Compose a full ChatResponse using the LLM.

        Args:
            query: The original clinical query.
            ranked_chunks: Ranked (chunk, score) tuples from RankingService.
            citations: Citations from CitationService.
            safety_flags: Safety flags from SafetyRuleEngine.
            patient_case: Optional de-identified patient context.
            request_id: Optional request ID for audit tracking.

        Returns:
            Complete ChatResponse object.
        """
        start_ms = int(time.time() * 1000)
        req_id = request_id or str(uuid.uuid4())

        chunks = [chunk for chunk, _ in ranked_chunks]
        context_block = _build_context_block(chunks)

        has_critical = any(f.severity == "critical" for f in safety_flags)
        disclaimer = _ESCALATED_DISCLAIMER if has_critical else _STANDARD_DISCLAIMER

        answer_text = self._call_llm(query, context_block, safety_flags, patient_case)

        # Compute confidence from tier scores
        from knowledge.scoring.confidence import compute_confidence, evidence_summary
        tier_scores = [chunk.metadata.evidence_tier_default for chunk in chunks]
        confidence = compute_confidence(chunks, query, tier_scores)
        ev_summary = evidence_summary(chunks, confidence)

        recommendations = self._extract_recommendations(answer_text)

        latency = int(time.time() * 1000) - start_ms

        return ChatResponse(
            answer=answer_text,
            recommendations=recommendations,
            citations=citations,
            safety_flags=safety_flags,
            confidence=confidence,
            evidence_summary=ev_summary,
            disclaimer=disclaimer,
            request_id=req_id,
            latency_ms=latency,
        )

    def _call_llm(
        self,
        query: str,
        context_block: str,
        safety_flags: list[SafetyFlag],
        patient_case: Optional[PatientCase],
    ) -> str:
        """Call the LLM with the assembled prompt.

        Falls back to a structured fallback message if the LLM is unavailable.

        Args:
            query: Clinical query.
            context_block: Formatted evidence context.
            safety_flags: Any triggered safety flags.
            patient_case: Optional patient context.

        Returns:
            LLM-generated answer string.
        """
        try:
            from langchain_openai import ChatOpenAI  # type: ignore[import]
            from langchain_core.messages import HumanMessage, SystemMessage  # type: ignore[import]

            llm = ChatOpenAI(
                model=self.model,
                temperature=self.temperature,
                api_key=self.openai_api_key or None,
            )

            system_content = self._system_prompt or (
                "You are a clinical decision support assistant specialising in peptide therapy. "
                "Provide evidence-based, citation-first responses. Always disclose uncertainty."
            )

            if safety_flags and self._safety_guardrails:
                system_content += "\n\n" + self._safety_guardrails

            patient_context = ""
            if patient_case:
                patient_context = (
                    f"\n\nPatient Context (de-identified):\n"
                    f"  Age range: {patient_case.age_range or 'not specified'}\n"
                    f"  Indications: {', '.join(patient_case.indications) or 'none'}\n"
                    f"  Contraindications: {', '.join(patient_case.contraindications) or 'none'}\n"
                )

            human_content = (
                f"Clinical Query: {query}"
                f"{patient_context}\n\n"
                f"Evidence Context:\n{context_block}"
            )

            messages = [
                SystemMessage(content=system_content),
                HumanMessage(content=human_content),
            ]

            response = llm.invoke(messages)
            return str(response.content)

        except ImportError:
            logger.warning("langchain_openai not available — returning fallback answer")
        except Exception as exc:
            logger.error("LLM call failed: %s", exc)

        # Fallback: structured answer from context only
        return self._fallback_answer(query, context_block)

    @staticmethod
    def _fallback_answer(query: str, context_block: str) -> str:
        """Generate a structured fallback answer when LLM is unavailable."""
        return (
            f"**Query:** {query}\n\n"
            f"**Note:** LLM synthesis is currently unavailable. "
            f"The following evidence was retrieved:\n\n{context_block}\n\n"
            "Please review the cited sources directly."
        )

    @staticmethod
    def _extract_recommendations(answer_text: str) -> list[str]:
        """Extract bullet-point recommendations from the answer text.

        Looks for lines starting with common recommendation markers.
        Returns a list of recommendation strings.
        """
        recommendations: list[str] = []
        for line in answer_text.split("\n"):
            stripped = line.strip()
            if stripped.startswith(("- ", "* ", "• ", "→ ")):
                rec = stripped.lstrip("-*•→ ").strip()
                if rec and len(rec) > 10:
                    recommendations.append(rec)
        return recommendations[:5]  # Cap at 5 recommendations
